name: Build & Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: splord/labelkitchen

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Docker Tag (commit hash + date)
        id: version
        run: |
          DATE=$(date +"%Y%m%d")
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "tag=${DATE}-${SHORT_SHA}" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ steps.version.outputs.tag }}
